### ISSUE TITLE
IoC release

### ISSUE THREAD

**Issue by sagacity** [ThatRendle/Simple.Web#1]
`ISimpleContainer` current only has a `Get` method, but it might be very useful to have a way of releasing components as well.

For instance, when using objects that are not thread-safe I would want to be able to create them when a handler starts and release them at the end of the handler, so they don't get reused by another request in the threadpool.

One of the ways this can be done is by exposing a nested container approach. In NInject this is called an activation block I believe, and in StructureMap this is called, well, a nested container (I'm sure you can guess which container I'm currently using :)).

**Comment by ThatRendle** [comment]
If you fancy writing a StuctureMap plug-in with this functionality, and bung me a pull request with the interface change, that'd be awesome. :)

**Comment by sagacity** [comment]
Okay, I'll give that a shot! Am I right in assuming that the main changes need to go in HandlerRunnerBuilder?

**Comment by ThatRendle** [comment]
If it needs to call the release thing, then yes, that's where it would
go, I guess after the Response blocks.

Sent from my iPad

On 10 Jun 2012, at 17:24, Roy Jacobs
reply@reply.github.com
wrote:

**Comment by sagacity** [comment]
Well, this is done, then.

**Comment by ThatRendle** [comment]
Indeed, and thank you very much, which I notice I have heretofore singularly failed to say.

**Comment by sagacity** [comment]
Thanks, of course! I'm eagerly awaiting your next step. Perhaps a roadmap blogpost would be nice? :)
