### ISSUE TITLE
Simple.Web.AspNet broken?

### ISSUE THREAD

**Issue by squidge** [ThatRendle/Simple.Web#15]
1. Asp.net empty web app
2. Add Reference
3. Simple.Web.AspNet
   adds this to web.config
   <httpHandlers>
     <add verb="*" path="*" type="Simple.Web.AspNet.SimpleHttpAsyncHandler" />
   </httpHandlers>
   among other stuff
4. Run
   Server application error: Could not load type 'Simple.Web.AspNet.SimpleHttpAsyncHandler'.

If I removed that I get the directory listing page. Am I missing something?

**Comment by ThatRendle** [comment]
Argh, that's old code showing up, that is. Change it to Fix.AspNet.FixHttpHandler, assembly Fix.AspNet.
