### ISSUE TITLE
Discuss: change to Input?

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Web#16]
I'm wondering if the IInput<T> interface with an Input property might be a bit crufty, and whether having IPost<T>, IPut<T> and so on might be better?

**Comment by ThatRendle** [comment]
Comparative code:

Current:

```
public class PostThing : IPost, IInput<Thing>
{
    public Status Post()
    {
        Save(Input);
        return Status.NoContent;
    }

    public Thing Input { private get; set; }
}
```

Proposed:

```
public class PostThing : IPost<Thing>
{
    public Status Post(Thing thing)
    {
        Save(thing);
        return Status.NoContent;
    }
}
```

**Comment by martin308** [comment]
That looks better to me, much clearer what is going on

**Comment by richardhopton** [comment]
There are occasions where a bodyless POST or PUT are required so as long as the existing IPost & IPut are still usable.

**Comment by squidge** [comment]
agree with @richardhopton IPost<Optional> would be nice

**Comment by ToJans** [comment]
+1

**Comment by ThatRendle** [comment]
Indeed, there would still be empty versions of every method.

**Comment by ThatRendle** [comment]
Done (in 0.5 branch).
