### ISSUE TITLE
Autofac Module doesn't not register generic interfaces

### ISSUE THREAD

**Issue by carcer** [ThatRendle/Simple.Web#33]
Ran into the same issue writing a Castle container.  None of the generic interfaces are registered (IPost<T>, etc.)

**Comment by ianbattersby** [comment]
Chris not sure I'm on the same wavelength, are you expecting the generic wire-up interfaces to be injectable as dependencies? Do you have a code sample? I'm likely being dim but I wouldn't do that.

**Comment by ianbattersby** [comment]
Chris I think this was crossed wires so am closing; apologies if I've misjudged.
