### ISSUE TITLE
ContinueWithHandler in AsyncPipeline misses unwrap

### ISSUE THREAD

**Issue by danielmarbach** [ThatRendle/Simple.Web#37]
Not sure about this but I think that

private static Task<bool> ContinueWithHandler<THandler>(Task<bool> task, Func<THandler, IContext, Status> continuation, IContext context, THandler handler)

misses the Unwrap of the task

**Comment by ThatRendle** [comment]
No, that method is continuing the pipeline with a not-asynchronous block, so the result is a Task<bool>, not a Task<Task<bool>>, and no Unwrap is needed.
