### ISSUE TITLE
Support OWIN

### ISSUE THREAD

**Issue by davidfowl** [ThatRendle/Simple.Web#4]
Instead of building multiple hosts for Simple.Web, take advantage of OWIN (http://owin.org/).

**Comment by ThatRendle** [comment]
Yes, I'm a big fan of OWIN, and it will be the second hosting option to become available. Waiting on the next draft at the moment.

If OWIN becomes able to support everything from IIS to nginx, then I'll be able to ditch all the other options.

**Comment by davidfowl** [comment]
It shouldn't be a second hosting option, it should be the only hosting option. I understand it's early, but builders of web frameworks need to just take the leap. The only way it'll get better is if we make it better. SignalR's next version is going to be an Owin only Server. 

It's fine to have n hosts yourself right now but that'll make it hard to interoperate with other frameworks in the long run. It should be seen as a stop gap until the OWIN spec is done.

Just my 2c.

**Comment by ThatRendle** [comment]
You know what, you're right. And I've just been looking at Gate, which gets OWIN working over a bunch of things including ASP.NET, so this has just made it to the top of my list.

**Comment by i-e-b** [comment]
I've got a _very_ rough `Simple.Web->OWIN->Firefly` test going on my branch (See SelfHost project);
Owin certainly introduces a few rough edges in the way it encapsulates things (esp. writing). Will continue to cleanup and improve today and tomorrow.

**Comment by ThatRendle** [comment]
Excellent stuff. I hope you've pulled all my upstream changes making everything asynchronous?

**Comment by i-e-b** [comment]
Yes, will keep tracking your upstream and submit a PR once the OWIN stuff is less of a mess

**Comment by ThatRendle** [comment]
I've been working on some uploaded file handling code, got a working version here: https://gist.github.com/2967190 if you want to integrate it.

**Comment by i-e-b** [comment]
Working on POST support through OWIN, I'm coming the the painful conclusion that OWIN has already become a fragmented mess. None of the hosts seem to be compatible, the Gate project is all over the place and simply reading posted data is a nightmare.
P.S. -- have at least the Firefly version semi-working now.

**Comment by ThatRendle** [comment]
Oh, that's not a good conclusion. I hope you don't mind, I've forwarded your comments to the mailing list, if you'd like to discuss this further with the OWIN guys the thread is here: https://groups.google.com/forum/m/#!topic/net-http-abstractions/O1uSqdXyJgo - I'm sure your input would be valuable.

**Comment by i-e-b** [comment]
Sure.
I figured out how to read POSTs after working out that OWIN 0.7.0.0 == 1.0 draft 4.
The Gate project doesn't line up to any of the drafts, and the head is beyond the current drafts, with no branches I can see.

The idea of OWIN is sound enough, but it could be more focused.
I'm going to keep ploughing on, because the more I work with Simple.Web the more I like it, but I have to support Mono.
I've got pretty solid forks of Kayak and Firefly (Slightly worrying that the main trunks are months old but unfinished)

**Comment by ThatRendle** [comment]
OK, I pulled those changes. I'll do some work on getting OWIN over ASP.NET and HttpListener up and running. I've already got a fairly large project running on Simple.Web which I'm using as a test reference at the moment, so if I can get that working under OWIN, we're getting somewhere.

**Comment by i-e-b** [comment]
Hi Mark.
Was continuing with Cookies last night, and it seemed that the ISetCookies wasn't writing cookies out to the context (it had a request implementation, but not a response one). I've added a WriteResponseCookie impl for this.

Just wanted to check this is right before I go messing up the codebase!

Cheers.

**Comment by ThatRendle** [comment]
Argh, no, sorry, I completely changed the way Cookies work. They're handled by a [Cookie] attribute on properties on the class, which causes the property to be set from the Request headers, and if the value changes during the lifecycle of the request, it is set back to the Response headers. Absolute fail on my part that the interface is still in there, very sorry.

**Comment by i-e-b** [comment]
No worries, cheers for the reply.
Will have a poke about and take my hacks and the old interface out.
The change is good in a way -- makes the interface easier!

**Comment by ThatRendle** [comment]
Right, it supports OWIN. Sort of. It doesn't support the latest draft, because it's all gone a bit wonky and structs and interfaces have appeared all over the place, which doesn't seem right to me. So it supports OWIN without those things. Check out [Flux](http://github.com/markrendle/Flux) and also [Fix](http://github.com/markrendle/Fix) for more.

**Comment by i-e-b** [comment]
Excellent. Are we around OWIN 5 then?

**Comment by ThatRendle** [comment]
We're kind of at [Draft 7](http://owin.org/spec/owin-1.0.0draft7.html), but I've destructured the CallParameters and RequestParameters structs, and changed things so you don't need to use IAppBuilder. I'm going to test Fix and Flux on Mono, to make sure that Flux works and see if Fix will work with xsp4.
