### ISSUE TITLE
Mono CI Build Agent

### ISSUE THREAD

**Issue by ianbattersby** [ThatRendle/Simple.Web#42]
Need a Mono CI build agent to ensure build quality and stability.

**Comment by ThatRendle** [comment]
If I spin up a Linux VM on Azure and give you ssh access, and admin on the Simple.Web project on TeamCity, do you reckon you can get it set up and working?

**Comment by ianbattersby** [comment]
Yep, no worries.

**Comment by ianbattersby** [comment]
Let me know.
