### ISSUE TITLE
Open For Extension ... Your thoughts.

### ISSUE THREAD

**Issue by bchavez** [ThatRendle/Simple.Web#55]
Hi,

I like Simple.Web's simplicity. However, I'm looking to extend the functionality.

After taking a look at `Simple.Web.Application` it seems kinda hard.

I'd like access to the routing table to determine if a route exists.

If the route does not exist, I'd like to have a "catch all" route that will process the request.

In an ideal world & work flow, I'd love to have the following directory layout for my website:

```
.
|-- Web.config
|-- _layout.cshtml
|-- index.cshtml
|-- about.cshtml
|-- contact.cshtml
|-- api
|   `-- search.cs
|-- account
|   |-- AuthenticatedAccount.cs
|   |-- _layout.cshtml
|   |-- dashboard
|   |   |-- index.cs
|   |   `-- index.cshtml
|   |-- contacts
|   |   |-- add.cs
|   |   |-- add.cshtml
|   |   `-- index.cshtml
|   `-- reports
|-- search
    `-- index.cshtml
```
#### 1. Custom Routing

As a startup task, I'd like to "override" the route finding mechanism in `Simple.Web`. In my mapping strategy I wouldn't rely on `[UriTemplate]` to build my routes... I would want to map IPost and IGet (and others) automatically based on the actual directory structure.
#### 2. No Drama Razor Pages & Layouts

I'd like to simply "drop in" a `cshtml` file in any location -- and have it automatically served. Currently, I have to go through a Handler in order to get a page served. Even if it's a simple IGet request that displays some general information.

Sure, I can use static HTML files, but then I lose the ability to leverage site-wide layouts and creating simple dynamic pages.
#### 3. Using `Simple.Web` _when_ I want it

The `/account/contacts` has the following files:

```
|   |-- contacts
|   |   |-- add.cs
|   |   |-- add.cshtml
|   |   `-- index.cshtml

public class add : AuthenticatedAccount, IPost<Contact>{
    public Status Post(Contact c){
         // add the contact.
    }
}
```
- A `GET /contacts` would render `index.cshtml`.
- A `GET /contacts/add` would render `add.cshtml` since there's no `IGet` on the `add` handler.
- A `POST /contacts/add` would execute `add.cs` as normal, then the handler would be given to `add.cshtml` for rendering.
- A `POST /contacts` would not execute any handlers, but it would render `/contacts/index.html` and post data would be available to the page if it wanted it.

Maybe what I'm looking for isn't in the perview of `Simple.Web`, but at a very minimum, it would be cool to have the ability to access/modify the routing table, access the razor engine, and have the ability to do **before** and **after** processing a handler is executed, and/or some kind of `{catchall}` mechanism.

Your thoughts?
Brian

**Comment by ThatRendle** [comment]
The routing thing seems like a pretty fundamental change, don't really see that happening.

I quite like the idea of cshtml files being picked up without handlers, though.

**Comment by ianbattersby** [comment]
Just to add that I am due to finish some work on the Razor engine that would allow you to render pages outside of the pipeline (the original requirement being partials); however I can't be definite on timeline.

I really like your idea of picking up index.cshtml, we have a similar structure and had been coming to a similar conclusion, so :+1: 

Thanks.
