### ISSUE TITLE
Add file watch to the razor files

### ISSUE THREAD

**Issue by mastoj** [ThatRendle/Simple.Web#86]
When a razor file is compiled it would be nice if a file watch got added to it so changes in the razors could be caught immediately when doing development without the need for a full recompile of the project.

**Comment by ThatRendle** [comment]
I think it's more a matter of just not caching the compiled views when running in Debug mode. Ian?

**Comment by ianbattersby** [comment]
Just set "ViewCache:Enabled" to false in the web.config and you can edit live. I think that's the setting anyway, check the sandbox project.

We set that for debug and true for release.

**Comment by mastoj** [comment]
cool!

**Comment by ianbattersby** [comment]
Gonna close this now dude as I think we are good. Re-open if not.
