### ISSUE TITLE
rake fails to build one project

### ISSUE THREAD

**Issue by mastoj** [ThatRendle/Simple.Web#87]
I've been having some problems with using rake which I can't figure out. Everything works just fine when building in Visual Studio but when building with rake I get the following error:

```
"C:\dev\git\Simple.Web\src\Simple.Web.sln" (Clean;Build target) (1) ->
"C:\dev\git\Simple.Web\src\Tests\DefaultSimpleContainer.Test\DefaultSimpleContainer.Test.csproj" (default target) (3:2) ->
(CheckPrerequisites target) ->
C:\dev\git\Simple.Web\src\.nuget\NuGet.targets(77,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Build.Tasks.v4.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Build.Tas ks.v4.0.dll' or one of its dependencies. The system cannot find the file specified
[C:\dev\git\Simple.Web\src\Tests\DefaultSimpleContainer.Test\DefaultSimpleC ontainer.Test.csproj]
```

It seems like when the project DefaultSimpleContainer.Tests is built the MSBuildToolsPath points to the MSBuild bin folder, but for the other projects it is pointing to ...Microsoft.NET\Framework\v4.0.30319 where the missing dll is located. I noticed that the project is targeting 4.5, but changing to 4 didn't help for me. I've been looking for a MSBuild<Param> that is pointing to the Framework folder instead of MSBuild\bin but haven't found one.

I'm running on Windows 8 with VS12 and VS13 preview installed if that is relevant. 

**Workaround:**
Copy the Microsoft.Build.Tasks.v4.0.dll from C:\Windows\Microsoft.NET\Framework\v4.0.30319 to C:\Program Files (x86)\MSBuild\12.0\Bin.

**Comment by ThatRendle** [comment]
It's the ToolsVersion in the csproj file. Because I'm using VS2013 now, the ToolsVersion on new projects gets set to 12.0 instead of 4.0. I've reset it in the source now, we'll have to look at getting this all working with 2013 projects soon.
