### ISSUE TITLE
No type was found called OwinAppSetup with a method taking a valid parameter type

### ISSUE THREAD

**Issue by finanstilsynetbygg** [ThatRendle/Simple.Web#92]
This might be a bug that should be filed in the Fix project, but I found it using Simple.Web. I'm trying to do the simplest thing possible, just create a "Hello world" project based on the empty web app template in Visual Studio. Step to recreate:
1. New empty web project
2. install-package Simple.Web
3. install-package Simple.Web.AspNet
4. F5, run --> Boom!

I have the default OwinAppSetup class, added by Fix.AspNet I think(?). So there's something weird going on here.

**Comment by mastoj** [comment]
The issue was created by me, I accidently was logged in with our "build user" when registering the issue.

**Comment by ghost** [comment]
This is the issue I thought https://github.com/markrendle/Simple.Web/issues/89 was commenting on. I have stepped through Fix with the debugger with this exact setup and get different results than if you just let it run. Almost seems like there might be a race condition somewhere, but I'm not sure. At any rate, I'm experiencing this as well. =)

**Comment by ThatRendle** [comment]
I'll be pushing a new release very soon which fixes this issue.

**Comment by ThatRendle** [comment]
Latest release fixes this issue.
